# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano', '0001_initial'),
        ('outro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nasc', models.DateField(blank=True, default=False, null=True)),
                ('data_venc', models.DateField(blank=True, default=False, null=True)),
                ('queixa', models.CharField(blank=True, max_length=500, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=500, null=True)),
                ('ativo', models.CharField(choices=[('1', 'Sim'), ('2', 'Nao')], max_length=1)),
                ('plan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
                ('prof1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outro.professor')),
            ],
        ),
    ]
