# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='plan1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plano.plano'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prof1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outro.professor'),
        ),
    ]
