# Generated by Django 2.0.7 on 2018-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=5)),
                ('data', models.CharField(max_length=10)),
            ],
        ),
    ]
