# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('outro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('prof1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outro.professor')),
            ],
        ),
    ]
