# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180716_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='presenca',
            field=models.CharField(choices=[(b'0', b'Nao'), (b'1', b'Sim')], default=0, max_length=1),
        ),
    ]
