# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20180716_1823'),
        ('outro', '0001_initial'),
        ('agenda', '0003_agendamento_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento_2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('presenca', models.CharField(choices=[(b'0', b'Nao'), (b'1', b'Sim')], default=0, max_length=1)),
                ('alunos', models.ManyToManyField(to='paciente.paciente')),
                ('prof1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outro.professor')),
            ],
        ),
    ]
