# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0003_auto_20180622_2005'),
        ('plano', '0001_initial'),
        ('paciente', '0003_remove_paciente_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='plan1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plano.plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='prof1',
            field=models.ForeignKey(default=10091991, on_delete=django.db.models.deletion.CASCADE, to='outro.professor'),
            preserve_default=False,
        ),
    ]
