# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0004_auto_20180626_1043'),
        ('outro', '0003_auto_20180622_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('prof1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outro.professor')),
            ],
        ),
    ]
