# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
