# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0002_auto_20180622_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_nasc',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
